### PR TITLE
feat: STX and stacking snapshot proposal voting extensions

### PR DESCRIPTION
**Pull request by MarvinJanssen**
This concept PR adds two new kind of voting contracts:

**EDE006 Snapshot Proposal Voting**

This concept extension allows anyone with STX to vote on proposals. The maximum upper bound, or voting power, depends on the amount of STX tokens the `tx-sender` owned at the start block height of the proposal. The name "snapshot" comes from the fact that the extension effectively uses the STX balance sheet at a specific block heights to determine voting power.

**EDE007 Stacking Snapshot Proposal Voting**

Same as EDE006, but allows voting based on the amount of STX being stacked by the `tx-sender` at the start block height of the proposal.

### CODE REVIEW

**Comment by mijoco-btc** [comment]
If there were two proposals submitted at blocks 10 and 15 say and I have an account with 1000 stx from block 5 then I'll be able to vote '1000' on both proposals?

And if I transferred 500 at block 12 then vote at block 30 say then I can vote 1000 for first proposal but only 500 for second?

**Comment by MarvinJanssen** [comment]
>If there were two proposals submitted at blocks 10 and 15 say and I have an account with 1000 stx from block 5 then I'll be able to vote '1000' on both proposals?

Correct.

>And if I transferred 500 at block 12 then vote at block 30 say then I can vote 1000 for first proposal but only 500 for second?

Correct.

And likewise, if you have a 1000 STX balance at block height 10, and then a proposal is submitted at block 15, and you buy an additional 500 STX at block 20, then your voting power for the proposal is still 1000 STX.

**Comment by mijoco-btc** [comment]
@MarvinJanssen is this suggestion only intended to impact the bootstrapping process - e.g. for enabling votes on the initial processes e.g. emergency team settings, activating treasury / token sale extensions etc? Is the intention that the voting thereafter reverts to the current locking/unlocking edg mechanism or would this replace or run in parallel even? If so we also need to figure out the implications for dependant features like delegation, proposal submission and son on?

**Comment by Hero-Gamer** [comment]
> @MarvinJanssen is this suggestion only intended to impact the bootstrapping process - e.g. for enabling votes on the initial processes e.g. emergency team settings, activating treasury / token sale extensions etc? Is the intention that the voting thereafter reverts to the current locking/unlocking edg mechanism or would this replace or run in parallel even? If so we also need to figure out the implications for dependant features like delegation, proposal submission and son on?

Hi @radicleart I think it's to prevent mis-use or re-use of tokens even if you transfer to another address. 
See the conversation in megapont's dao: 
Starting with Francisc's comment, down to Jamil's reply:
https://discord.com/channels/893027129602740264/994008104926728323/996812011176460360
(You'll need to join Megapont's server if you wanna see the messages)

**Comment by mijoco-btc** [comment]
Yes - I cant see that. Is there an invite link?

**Comment by mijoco-btc** [comment]
Moving this comment from discord to here..

submitting normal (and emergency) proposals is hard wired right now to EDE-001 - @MarvinJanssen 
 do you have a solution in mind for this? The caller to propose could pass in the extension to use for voting - feels like that would mean the proposal data should really be in the submission contract - or the client could poll each voting extension to see if it owns the proposal?

The governance token could be removed and set (or not as the case may be) in the voting extension in the way Lnow suggested?


```(define-public (propose (proposal <proposal-trait>) (voting-extension <extension-trait>) (start-block-height uint) (governance-token <governance-token-trait>))
    (begin
        (try! (is-governance-token governance-token))
        (asserts! (as-contract (contract-call? .executor-dao is-extension voting-extension)) err-voting-not-valid-extension)
       ...
        (contract-call? voting-extension add-proposal
            proposal
            {
                start-block-height: start-block-height,
                end-block-height: (+ start-block-height (try! (get-parameter "proposal-duration"))),
                proposer: tx-sender
            }
        )
    )
)```

**Comment by mijoco-btc** [comment]
Instead of changing ede-002-proposal-submission maybe its better to have a new extension for submitting proposals - ede-007-snapshot-proposal-submission ?

The submission criteria could be reworked - e.g. to implement the idea of crowd funding support for a proposal ?

**Comment by MarvinJanssen** [comment]
A new concept contract has been added that allows voting based on the amount of STX being stacked by the voter at the start height of the proposal. The extension contract is tentatively called `ede007-stacking-snapshot-proposal-voting.clar`.

**Comment by mijoco-btc** [comment]
Closing this as this feature has been merged with the feat/baseline branch unit tested and function tested on stacks testnet.

**Pull request closed without merging**
